name: Publish package

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release v')"

    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js build environment
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      # Cache dependencies
      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            **/node_modules
          key: yarn-${{ hashFiles('**/package.json', 'yarn.lock') }}

      # Install project dependencies
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      # Build the project
      - name: Build
        run: yarn build

      # Authenticate to NPM
      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      # Release and publish version
      - name: Release version
        run: yarn release --ci --npm.skipChecks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
